import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import AboutSection from "../components/HomePageComponents/AboutSection";
import AmentSection from "../components/HomePageComponents/AmentSection";
import ContactSection from "../components/HomePageComponents/ContactSection";
import OfferSection from "../components/HomePageComponents/OfferSection";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <AmentSection />
        <div className={styles.line} />
        <AboutSection />
        <div className={styles.line} />
        <OfferSection />
        <ContactSection />
      </div>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async (context) => {
  fetch("http://localhost:1337/api/posts")
    .then((res) => res.json())
    .then((data) => console.log(data.data, data.meta))
    .catch((err) => console.log(err));

  return {
    props: {}, // will be passed to the page component as props
  };
};
